version: '3.8'

services:
  broker-bot-old:
    build: .
    container_name: broker-bot-old
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
